version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-minor"]
